logging:
  version: 1

  formatters:
    default:
      format: '%(asctime)s %(levelname)s %(module)s/#%(process)x %(message)s'

  handlers:
    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: default

  loggers:
    '':
      handlers: [stderr]
      level: DEBUG # CRITICAL, ERROR, WARNING, INFO, DEBUG


model:
  is_train: True

  # for model building
  num_classes: 100
  input_shape: [32, 32, 3]

  # for training
  path_to_tensorboard_logs: 'tensorboard_logs'
  path_to_checkpoints: 'model-improvement-{epoch:02d}.hdf5'

  batch_size: 128
  epochs: 100
  decay: 0.0005
  learning_rate: 0.1